# Generated by Django 5.2.15 on 2026-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Optional image URL (used if no uploaded image).'),
        ),
    ]
